<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DestinationDestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['destination_id' => 1, 'to_destination_id' => 2, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 1, 'to_destination_id' => 3, 'jarak' => 44.3, 'waktu_tempuh' => 81],
            ['destination_id' => 1, 'to_destination_id' => 4, 'jarak' => 22.5, 'waktu_tempuh' => 54],
            ['destination_id' => 1, 'to_destination_id' => 5, 'jarak' => 43.2, 'waktu_tempuh' => 88],
            ['destination_id' => 1, 'to_destination_id' => 6, 'jarak' => 11.7, 'waktu_tempuh' => 24],
            ['destination_id' => 1, 'to_destination_id' => 7, 'jarak' => 33, 'waktu_tempuh' => 72],
            ['destination_id' => 1, 'to_destination_id' => 8, 'jarak' => 9.7, 'waktu_tempuh' => 30],
            ['destination_id' => 1, 'to_destination_id' => 9, 'jarak' => 5.4, 'waktu_tempuh' => 16],
            ['destination_id' => 1, 'to_destination_id' => 10, 'jarak' => 11.7, 'waktu_tempuh' => 24],
            ['destination_id' => 1, 'to_destination_id' => 11, 'jarak' => 10.1, 'waktu_tempuh' => 21],
            ['destination_id' => 1, 'to_destination_id' => 12, 'jarak' => 5.2, 'waktu_tempuh' => 15],
            ['destination_id' => 1, 'to_destination_id' => 13, 'jarak' => 1985, 'waktu_tempuh' => 5280],
            ['destination_id' => 2, 'to_destination_id' => 3, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 2, 'to_destination_id' => 4, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 2, 'to_destination_id' => 5, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 2, 'to_destination_id' => 6, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 2, 'to_destination_id' => 7, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 2, 'to_destination_id' => 8, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 2, 'to_destination_id' => 9, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 2, 'to_destination_id' => 10, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 2, 'to_destination_id' => 11, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 2, 'to_destination_id' => 12, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 2, 'to_destination_id' => 13, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 3, 'to_destination_id' => 4, 'jarak' => 1279, 'waktu_tempuh' => 3240],
            ['destination_id' => 3, 'to_destination_id' => 5, 'jarak' => 2.8, 'waktu_tempuh' => 13],
            ['destination_id' => 3, 'to_destination_id' => 6, 'jarak' => 55.8, 'waktu_tempuh' => 108],
            ['destination_id' => 3, 'to_destination_id' => 7, 'jarak' => 41.4, 'waktu_tempuh' => 90],
            ['destination_id' => 3, 'to_destination_id' => 8, 'jarak' => 37.1, 'waktu_tempuh' => 67],
            ['destination_id' => 3, 'to_destination_id' => 9, 'jarak' => 39.7, 'waktu_tempuh' => 75],
            ['destination_id' => 3, 'to_destination_id' => 10, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 3, 'to_destination_id' => 11, 'jarak' => 21.8, 'waktu_tempuh' => 39],
            ['destination_id' => 3, 'to_destination_id' => 12, 'jarak' => 40.3, 'waktu_tempuh' => 71],
            ['destination_id' => 3, 'to_destination_id' => 13, 'jarak' => 61.9, 'waktu_tempuh' => 100],
            ['destination_id' => 5, 'to_destination_id' => 6, 'jarak' => 54.7, 'waktu_tempuh' => 105],
            ['destination_id' => 5, 'to_destination_id' => 7, 'jarak' => 37.7, 'waktu_tempuh' => 86],
            ['destination_id' => 5, 'to_destination_id' => 8, 'jarak' => 36, 'waktu_tempuh' => 59],
            ['destination_id' => 5, 'to_destination_id' => 9, 'jarak' => 40.8, 'waktu_tempuh' => 68],
            ['destination_id' => 5, 'to_destination_id' => 10, 'jarak' => 54.7, 'waktu_tempuh' => 93],
            ['destination_id' => 5, 'to_destination_id' => 11, 'jarak' => 20.6, 'waktu_tempuh' => 34],
            ['destination_id' => 5, 'to_destination_id' => 12, 'jarak' => 39.1, 'waktu_tempuh' => 75],
            ['destination_id' => 5, 'to_destination_id' => 13, 'jarak' => 60.7, 'waktu_tempuh' => 85],
            ['destination_id' => 6, 'to_destination_id' => 7, 'jarak' => 44, 'waktu_tempuh' => 92],
            ['destination_id' => 6, 'to_destination_id' => 8, 'jarak' => 20.7, 'waktu_tempuh' => 53],
            ['destination_id' => 6, 'to_destination_id' => 9, 'jarak' => 16.4, 'waktu_tempuh' => 37],
            ['destination_id' => 6, 'to_destination_id' => 10, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 6, 'to_destination_id' => 11, 'jarak' => 33.7, 'waktu_tempuh' => 69],
            ['destination_id' => 6, 'to_destination_id' => 12, 'jarak' => 16.2, 'waktu_tempuh' => 34],
            ['destination_id' => 6, 'to_destination_id' => 13, 'jarak' => 48.8, 'waktu_tempuh' => 93],
            ['destination_id' => 7, 'to_destination_id' => 8, 'jarak' => 25.6, 'waktu_tempuh' => 54],
            ['destination_id' => 7, 'to_destination_id' => 9, 'jarak' => 28.1, 'waktu_tempuh' => 64],
            ['destination_id' => 7, 'to_destination_id' => 10, 'jarak' => 44.3, 'waktu_tempuh' => 94],
            ['destination_id' => 7, 'to_destination_id' => 11, 'jarak' => 33.1, 'waktu_tempuh' => 64],
            ['destination_id' => 7, 'to_destination_id' => 12, 'jarak' => 34.1, 'waktu_tempuh' => 67],
            ['destination_id' => 7, 'to_destination_id' => 13, 'jarak' => 45.4, 'waktu_tempuh' => 79],
            ['destination_id' => 8, 'to_destination_id' => 9, 'jarak' => 6.5, 'waktu_tempuh' => 19],
            ['destination_id' => 8, 'to_destination_id' => 10, 'jarak' => 22.7, 'waktu_tempuh' => 53],
            ['destination_id' => 8, 'to_destination_id' => 11, 'jarak' => 15.3, 'waktu_tempuh' => 28],
            ['destination_id' => 8, 'to_destination_id' => 12, 'jarak' => 21, 'waktu_tempuh' => 8.2],
            ['destination_id' => 8, 'to_destination_id' => 13, 'jarak' => 28.1, 'waktu_tempuh' => 43],
            ['destination_id' => 9, 'to_destination_id' => 10, 'jarak' => 16.2, 'waktu_tempuh' => 33],
            ['destination_id' => 9, 'to_destination_id' => 11, 'jarak' => 18.2, 'waktu_tempuh' => 38],
            ['destination_id' => 9, 'to_destination_id' => 12, 'jarak' => 0.2, 'waktu_tempuh' => 3],
            ['destination_id' => 9, 'to_destination_id' => 13, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 10, 'to_destination_id' => 11, 'jarak' => 20.5, 'waktu_tempuh' => 39],
            ['destination_id' => 11, 'to_destination_id' => 12, 'jarak' => 1240, 'waktu_tempuh' => 3180],
            ['destination_id' => 11, 'to_destination_id' => 13, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 12, 'to_destination_id' => 13, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 14, 'to_destination_id' => 15, 'jarak' => 4.3, 'waktu_tempuh' => 33],
            ['destination_id' => 14, 'to_destination_id' => 16, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 14, 'to_destination_id' => 17, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 14, 'to_destination_id' => 18, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 14, 'to_destination_id' => 19, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 14, 'to_destination_id' => 20, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 14, 'to_destination_id' => 21, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 14, 'to_destination_id' => 22, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 15, 'to_destination_id' => 16, 'jarak' => 15.3, 'waktu_tempuh' => 61],
            ['destination_id' => 15, 'to_destination_id' => 17, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 15, 'to_destination_id' => 18, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 15, 'to_destination_id' => 19, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 15, 'to_destination_id' => 20, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 15, 'to_destination_id' => 21, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 15, 'to_destination_id' => 22, 'jarak' => 450, 'waktu_tempuh' => 1],
            ['destination_id' => 16, 'to_destination_id' => 17, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 16, 'to_destination_id' => 18, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 16, 'to_destination_id' => 19, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 16, 'to_destination_id' => 20, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 16, 'to_destination_id' => 21, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 16, 'to_destination_id' => 22, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 17, 'to_destination_id' => 18, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 17, 'to_destination_id' => 19, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 17, 'to_destination_id' => 20, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 17, 'to_destination_id' => 21, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 17, 'to_destination_id' => 22, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 18, 'to_destination_id' => 19, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 18, 'to_destination_id' => 20, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 18, 'to_destination_id' => 21, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 18, 'to_destination_id' => 22, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 19, 'to_destination_id' => 20, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 19, 'to_destination_id' => 21, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 19, 'to_destination_id' => 22, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 20, 'to_destination_id' => 21, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 20, 'to_destination_id' => 22, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 21, 'to_destination_id' => 22, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 23, 'to_destination_id' => 24, 'jarak' => 0, 'waktu_tempuh' => 0],
            ['destination_id' => 25, 'to_destination_id' => 26, 'jarak' => 0, 'waktu_tempuh' => 0],
        ];

        DB::table('destination_destination')->insert($data);
    }
}
